name: love
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  after_layout: ^1.2.0
  gap: ^3.0.1
  styled_widget: ^0.4.0+3
  loader_overlay: ^4.0.0
  page_transition: ^2.1.0
  flutter_native_splash: ^2.3.10
  flutter_svg: ^2.0.4
  modal_bottom_sheet: ^3.0.0-pre
  june:
  hive:
  hive_flutter:
  go_router: ^13.2.0
  event_bus: ^2.0.0
  flutter_speed_dial: ^7.0.0
  flutter_screenutil: ^5.5.3+2

  easy_localization: ^3.0.3
  easy_localization_loader: ^2.0.0

  device_preview: ^1.1.0

  permission_handler: ^11.0.1
  awesome_notifications: ^0.8.2
  infinite_listview: ^1.1.0
  flutter_spinkit: ^5.2.0

  flutter_fgbg: ^0.3.0
  flutter_easyloading: ^3.0.5
  flutter_phoenix: ^1.1.1

  logger: ^2.0.2+1

  package_info_plus: ^5.0.1

  junes_flutter_architecture:
    git:
      url: https://github.com/melodysdreamj/junes_flutter_architecture_pakage.git

  timeago: ^3.6.1

  flutter_zoom_drawer: ^3.2.0
  keyboard_attachable: ^2.2.0

  bot_toast: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.13.1
  import_sorter: ^4.6.0
  flutter_lints: ^3.0.1
  flutter_gen_runner: ^5.1.0+1
  test: ^1.17.12
  flutter_oss_licenses: ^2.0.0+1


  emulators: ^0.5.1
  freezed: ^2.0.3+1
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/localization.csv

flutter_icons:
  image_path_android: "assets/launcher_icons/android.png"
  image_path_ios: "assets/launcher_icons/ios.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/launcher_icons/android.png" # only available for Android 8.0 devices and above


flutter_native_splash:
  color: "#ffffff"
  #background_image: "assets/splash/background.png"
  image: assets/splash/icon.png

  color_dark: "#ffffff"
  ##background_image_dark: "assets/dark-background.png"
  image_dark: assets/splash/icon.png

  #android: false
  #ios: false
  #web: false

  #android_gravity: center
  #ios_content_mode: center
  #web_image_mode: center

  fullscreen: true
